name: Nuestro primer pipeline
on:
  pull_request: 
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Analisis del proyecto
    - name: Ejecutamos un comando
      run: echo Esta ejecutando el pipeline
    - name: Ejecutamos varias lineas
      run: |
        echo Varias lineas
        ls -la
    
